# Generated by Django 3.0.8 on 2021-07-25 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=122)),
                ('club_category', models.CharField(choices=[('Bollywood', 'Bollywood'), ('HipHop', 'HipHop'), ('Dance', 'Dance'), ('Party', 'Party')], max_length=20)),
                ('club_address', models.CharField(default='Vinay Building Road, Kandiwali West', max_length=122)),
                ('club_city', models.CharField(max_length=30)),
                ('club_zip_code', models.IntegerField(default=785412)),
                ('club_about', models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.")),
                ('club_image', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('menus_image', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('ambience_image1', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('ambience_image2', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('club_reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_Event',
            fields=[
                ('c_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_event_name', models.CharField(max_length=122)),
                ('c_event_date', models.DateField()),
                ('c_event_time', models.TimeField()),
                ('male_price', models.IntegerField(default=250)),
                ('female_price', models.IntegerField(default=250)),
                ('couple_price', models.IntegerField(default=250)),
                ('c_event_about', models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.")),
                ('event_thumbnail', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist_image1', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist1', models.CharField(max_length=122)),
                ('artist_image2', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist2', models.CharField(max_length=122)),
                ('artist_image3', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist3', models.CharField(max_length=122)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=122)),
                ('event_address', models.CharField(default='Vinay Building Road, Kandiwali West', max_length=122)),
                ('event_city', models.CharField(max_length=30)),
                ('event_zip_code', models.IntegerField(default=785412)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_price', models.IntegerField(default=250)),
                ('event_about', models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.")),
                ('event_thumbnail', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist_image1', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist1', models.CharField(max_length=122)),
                ('artist_image2', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist2', models.CharField(max_length=122)),
                ('artist_image3', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('artist3', models.CharField(max_length=122)),
                ('event_image1', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_image2', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_image3', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_image4', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_image5', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_image6', models.ImageField(default='images\\sam-mar-OQOKSsj8QME-unsplash_yb1Q7yu.jpg', upload_to='images')),
                ('event_TC', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=122)),
                ('userissue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_Table_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(choices=[(6, 'Diamond Table'), (7, 'Platinum Table'), (8, 'Royal Table')], default=6, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('males', models.TextField(null=True)),
                ('females', models.TextField(null=True)),
                ('couples', models.TextField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club_Event_Table_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(choices=[(6, 'Diamond Table'), (7, 'Platinum Table'), (8, 'Royal Table')], default=6, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Club_Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club_Event_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('males', models.TextField(null=True)),
                ('females', models.TextField(null=True)),
                ('couples', models.TextField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Club_Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
