# Generated by Django 3.0.8 on 2021-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='ambience_image1',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club',
            name='ambience_image2',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_image',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club',
            name='menus_image',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club_event',
            name='artist_image1',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club_event',
            name='artist_image2',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club_event',
            name='artist_image3',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club_event',
            name='event_thumbnail',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist_image1',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist_image2',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist_image3',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image1',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image3',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image4',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image5',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image6',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_thumbnail',
            field=models.ImageField(default='/static/1.jpg', upload_to='images'),
        ),
    ]
