# Generated by Django 3.0.8 on 2021-07-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_event_booking',
            name='id',
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='booking_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
