# Generated by Django 3.0.8 on 2021-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210721_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_event_booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
