# Generated by Django 3.0.8 on 2021-07-21 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210721_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_event_booking',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='order_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
