# Generated by Django 3.0.8 on 2021-07-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210722_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_event_booking',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='club_event_booking',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
