# Generated by Django 3.0.8 on 2021-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210722_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_event_booking',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
    ]
