# Generated by Django 3.0.8 on 2021-07-22 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210722_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_event_booking',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 16, 22, 2, 135996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='club_event_booking',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 22, 16, 22, 2, 135996, tzinfo=utc)),
        ),
    ]
