# Generated by Django 3.0.8 on 2021-07-22 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210722_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_event_booking',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='club_event_booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 16, 58, 59, 462328, tzinfo=utc)),
        ),
    ]
