# Generated by Django 3.0.8 on 2021-07-22 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210722_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_event_booking',
            name='order_date',
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='finalbooking_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='club_event_booking',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 17, 18, 38, 225711, tzinfo=utc)),
        ),
    ]
