# Generated by Django 3.0.8 on 2021-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20210722_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_event_booking',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
