# Generated by Django 3.0.8 on 2021-07-22 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_auto_20210722_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Event_Table_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(choices=[(6, 'Diamond Table'), (7, 'Platinum Table'), (8, 'Royal Table')], default=6, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField()),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Club_Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
