# Generated by Django 3.0.8 on 2021-07-22 21:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_club_event_table_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_booking',
            name='finalbooking_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event_booking',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='event_booking',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 21, 58, 3, 96844, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Event_Table_Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(choices=[(6, 'Diamond Table'), (7, 'Platinum Table'), (8, 'Royal Table')], default=6, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2021, 7, 22, 21, 58, 3, 97790, tzinfo=utc))),
                ('finalbooking_id', models.CharField(default='', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Club_Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
