# Generated by Django 3.0.8 on 2021-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210723_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_booking',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event_table_booking',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
