# Generated by Django 3.0.8 on 2021-07-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20210723_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
