# Generated by Django 3.0.8 on 2021-07-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210723_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_table_booking',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Event'),
        ),
    ]
