# Generated by Django 3.0.8 on 2021-07-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20210725_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
